"use strict";

/**
 * Generate a v10 flat config based on analysis results.
 */
function generateConfig(analysis) {
  if (!analysis || !analysis.details) {
    return generateStarterConfig();
  }

  const compatibleRules = analysis.details
    .filter(d => d.status === "compatible")
    .map(d => ({ rule: d.rule, config: d.config }));

  const needReviewRules = analysis.details
    .filter(d => d.status === "needs-review" || d.status === "unknown")
    .map(d => ({ rule: d.rule, config: d.config }));

  let config = `// ESLint v10 flat config generated by @clearlint/eslint-migrate
// Review and adjust before using.
// Migration analysis: ${analysis.compatible}/${analysis.totalRules} rules compatible

import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    rules: {
`;

  for (const { rule, config: ruleConfig } of compatibleRules) {
    const val = ruleConfig !== null ? JSON.stringify(ruleConfig) : '"error"';
    config += `      "${rule}": ${val},\n`;
  }

  if (needReviewRules.length > 0) {
    config += `\n      // ⚠️  The following rules need manual review:\n`;
    for (const { rule } of needReviewRules) {
      config += `      // "${rule}": "off", // REVIEW: may have changed in v10\n`;
    }
  }

  config += `    },
  },
];
`;

  return config;
}

function generateStarterConfig() {
  return `// ESLint v10 flat config starter — generated by @clearlint/eslint-migrate
import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    rules: {
      // Add your project-specific rules here
    },
  },
];
`;
}

module.exports = { generateConfig };
